//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodesDecoder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodesDecoder.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARCODES DECODER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode format not supported yet.
        /// </summary>
        public static string BarcodeFormatNotSupportedText {
            get {
                return ResourceManager.GetString("BarcodeFormatNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin: .
        /// </summary>
        public static string BarcodeInfoCountryOfOriginLabel {
            get {
                return ResourceManager.GetString("BarcodeInfoCountryOfOriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode data is broken. Please try again or contact support..
        /// </summary>
        public static string BarcodeInfoDataIsNullErrorMessage {
            get {
                return ResourceManager.GetString("BarcodeInfoDataIsNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search by country or barcode first 3 digits.
        /// </summary>
        public static string BarcodeListSearchLabel {
            get {
                return ResourceManager.GetString("BarcodeListSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcode info.
        /// </summary>
        public static string BarcodesInfoPageTitle {
            get {
                return ResourceManager.GetString("BarcodesInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcodes list.
        /// </summary>
        public static string BarcodesListPageTitle {
            get {
                return ResourceManager.GetString("BarcodesListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t initialize camera.
        /// </summary>
        public static string CantInitCameraErrorText {
            get {
                return ResourceManager.GetString("CantInitCameraErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to focus camera on a barcode.
        /// </summary>
        public static string CaptureInstructionsText {
            get {
                return ResourceManager.GetString("CaptureInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture barcode.
        /// </summary>
        public static string CapturePageTitle {
            get {
                return ResourceManager.GetString("CapturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcodes.
        /// </summary>
        public static string MainMenuBarcodesListButtonText1 {
            get {
                return ResourceManager.GetString("MainMenuBarcodesListButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string MainMenuBarcodesListButtonText2 {
            get {
                return ResourceManager.GetString("MainMenuBarcodesListButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string MainMenuScanBarcodeButtonText1 {
            get {
                return ResourceManager.GetString("MainMenuScanBarcodeButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcode.
        /// </summary>
        public static string MainMenuScanBarcodeButtonText2 {
            get {
                return ResourceManager.GetString("MainMenuScanBarcodeButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main menu.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
